<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.1 setup script
 * Date: Thu, 19 Mar 2020 12:53:07 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: websoft365-1.cmqtatgyjf6h.eu-central-1.rds.amazonaws.com [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'websoft365-1.cmqtatgyjf6h.eu-central-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'Zolika1969';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'vR!XtH{UOmj\\l{p[\\VGj*\\Ivt@)*Y4P\'';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>